import type { Metadata } from 'next';
import { Open_Sans } from 'next/font/google';
import './globals.css';
import { ReactNode } from 'react';
import AuthProvider from '@/components/auth/AuthProvider';
import ClientOnly from '@/components/commons/ClientOnly';
import ReactQueryProviders from '../hooks/useReactQuery';
import Navbar from '@/components/commons/Navbar';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';

type Props = { children: ReactNode; modal: ReactNode };

const openSans = Open_Sans({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({ children, modal }: Props) {
  const session = await getServerSession(authOptions);
  const user = session?.user;
  return (
    <html lang="ko" className={`${openSans.className}`}>
      <body className="w-full flex overflow-auto">
        <AuthProvider>
          <ReactQueryProviders>
            {user && <Navbar />}
            <main className="w-full flex justify-cente h-full">{children}</main>
            {modal}
          </ReactQueryProviders>
        </AuthProvider>
        <div id="modal-root" />
      </body>
    </html>
  );
}
